# Generated by Django 4.0.6 on 2022-08-30 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Max_marks', models.IntegerField()),
                ('Max_duration', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('Tags', models.CharField(blank=True, choices=[('Technical', 'Technical'), ('SoftSkills', 'SoftSkills'), ('Presentations', 'Presentations'), ('Group Discussions', 'Group Discussions'), ('Problems Solving', 'Problem Solving'), ('Hacker Rank', 'Hacker Rank')], max_length=20, null=True)),
                ('Grades', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Mastery', 'Mastery'), ('Exemplary', 'Exemplary'), ('Incomplete', 'Incomplete'), ('Pending', 'Pending')], max_length=100, null=True)),
                ('Remarks', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('acadamicYear', models.CharField(choices=[('FirstYear', 'FirstYear'), ('SecondYear', 'SecondYear'), ('Alumni', 'Alumni')], max_length=20)),
                ('specalization', models.CharField(choices=[('Full Stack Webdevelopment', 'Full Stack Webdevelopment'), ('Machine Learning', 'Machine Learning'), ('Artifical Intelligence', 'Artifical Intelligence'), ('Data Science', 'Data Science'), ('Ethical Hacking', 'Ethical Hacking'), ('Cloud Computing', 'Cloud Computing')], max_length=50)),
                ('RollNumber', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Course_Unit_Relation', models.ManyToManyField(to='directoryPage.course')),
            ],
        ),
        migrations.CreateModel(
            name='Units_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Created_At', models.DateField(auto_now_add=True)),
                ('Image', models.ImageField(blank=True, upload_to='media')),
                ('Text_box', models.TextField(max_length=1000)),
                ('Units_UC_Relation', models.ManyToManyField(to='directoryPage.units')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Enrolled_Date', models.DateField(auto_now_add=True)),
                ('CourseKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directoryPage.course')),
                ('StudentKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directoryPage.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Course_Student_Relation',
            field=models.ManyToManyField(through='directoryPage.Enrollments', to='directoryPage.student'),
        ),
    ]
