# Generated by Django 4.0.6 on 2022-08-21 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('bio', models.TextField(max_length=400)),
                ('acadamicYear', models.CharField(choices=[('FirstYear', 'FirstYear'), ('SecondYear', 'SecondYear'), ('Alumni', 'Alumni')], max_length=20)),
                ('specalization', models.CharField(choices=[('Full Stack Webdevelopment', 'Full Stack Webdevelopment'), ('Machine Learning', 'Machine Learning'), ('Artifical Intelligence', 'Artifical Intelligence'), ('Data Science', 'Data Science'), ('Ethical Hacking', 'Ethical Hacking'), ('Cloud Computing', 'Cloud Computing')], max_length=50)),
                ('RollNumber', models.IntegerField()),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
                ('remarks', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], max_length=50)),
                ('courseEnrolledDate', models.DateField(auto_now_add=True)),
                ('courseDuration', models.IntegerField()),
                ('continousCredits', models.CharField(choices=[('SoftSkills', 'SoftSkills'), ('continousCredits-ss', 'continousCredits-ss'), ('continousCredits-ps', 'continousCredits-ps'), ('continousCredits-hk', 'continousCredits-hk'), ('Technical', 'Technical')], max_length=50)),
                ('studentKey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='directoryPage.studentcard')),
            ],
        ),
    ]
