# Generated by Django 4.0.6 on 2022-08-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directoryPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_to_be_Add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directoryPage.course')),
                ('Student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directoryPage.studentcard')),
            ],
        ),
    ]
