# Generated by Django 4.0.6 on 2022-07-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='continousCredits',
            field=models.CharField(choices=[('SoftSkills', 'SoftSkills'), ('continousCredits-ss', 'continousCredits-ss'), ('continousCredits-ps', 'continousCredits-ps'), ('continousCredits-hk', 'continousCredits-hk'), ('TechnicalWriting', 'TechnicalWriting'), ('ContinousCredits', 'ContinousCredits'), ('ContinousCredits_ProgrammingContest', 'ContinousCredits_ProgrammingContest'), ('ContinousCredits_ProblemSolving', 'ContinousCredits_ProblemSolving')], max_length=50),
        ),
    ]
