# Generated by Django 4.0.6 on 2022-08-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='Grades',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Mastery', 'Mastery'), ('Exemplary', 'Exemplary'), ('Incomplete', 'Incomplete'), ('Pending', 'Pending')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='Remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
