# Generated by Django 4.0.6 on 2022-08-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryPage', '0002_units_grades_units_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='Difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Advanced', 'Advanced')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
