# Generated by Django 4.0.6 on 2022-08-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directoryPage', '0003_units_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units_content',
            name='Units_UC_Relation',
        ),
        migrations.AddField(
            model_name='units_content',
            name='Units_UC_Relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directoryPage.units'),
            preserve_default=False,
        ),
    ]
