# Generated by Django 4.0.6 on 2022-08-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directoryPage', '0002_add_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='level2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=200)),
                ('total_topics', models.IntegerField()),
                ('result', models.CharField(choices=[('Mastery', 'Mastery'), ('Exmplary', 'Exmplary'), ('Satisfactory', 'satisfactory')], max_length=100)),
                ('courseKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directoryPage.course')),
            ],
        ),
    ]
